# Generated by Django 5.2.8 on 2026-04-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('therapist', 'Therapist'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
