# Generated by Django 5.2.8 on 2026-05-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapists', to='authentication.supervisor'),
        ),
    ]
