# Generated by Django 6.0.3 on 2026-04-24 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0002_therapyplan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_number", models.IntegerField()),
                ("date", models.DateField()),
                ("progress", models.TextField()),
                ("notes", models.TextField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="therapy.therapyplan",
                    ),
                ),
            ],
        ),
    ]
