# Generated by Django 6.0.3 on 2026-04-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0003_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
