# Generated by Django 6.0.3 on 2026-04-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0006_supervisorfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="supervisorfeedback",
            name="rating",
            field=models.IntegerField(default=1),
        ),
    ]
